import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')

const fontDir = resolve(root, 'node_modules/@fontsource/inter/files')

const fonts = [
  { weight: '400', file: 'inter-latin-400-normal.woff2' },
  { weight: '500', file: 'inter-latin-500-normal.woff2' },
  { weight: '600', file: 'inter-latin-600-normal.woff2' },
]

const entries = fonts.map(({ weight, file }) => {
  const data = readFileSync(resolve(fontDir, file))
  const base64 = data.toString('base64')
  return `  { weight: '${weight}', base64: '${base64}' }`
})

const content = `// Auto-generated by scripts/generate-font-data.ts — do not edit manually
export const fontData: Array<{ weight: string; base64: string }> = [
${entries.join(',\n')}
]
`

const outPath = resolve(root, 'src/workspace/export/font-data.ts')
writeFileSync(outPath, content, 'utf-8')
console.log(`Wrote font data to ${outPath}`)
